[paluh]
admin = true
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILd7mkXxI285N/pVRdbe/5WUTwj9iNnfUZ7BccEsE9ov",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnapIKESWeRy5P84tBvt3RUhUNT4pkpxtZBSWkTVus7uPkgg4c43Fp/s1xZdCj27o+65G08g7LVbGzWJS6QIqjj9D3vqsJ2n7iivNKWGEMld90XMKCx7xrkDcyoyEWopENAWwUd+2jixNgNuacgazYLie9CIuH6xh+CI29IFBAGdNRP/Fk3IUCn/rI6GlmTHm66cByMexj4cSP+Ts3gZa/fQ3ihvqrOxikTCBc0knwS6fVPnNvS0vfNxFbkDwlzOcwBX/c9b9BlXEqpKeBIb6uQmg8IUYq2HFN0uwBkeCZBudODFPj8tIsnej3G5jHHgssE4lxaQmM/hTb1JDBylVBAzPMQBsR5lSHlXAT6N2S8L4vFPPC7HQ7x3SFU2Ggu20T/DZnwDnGRpcNfprXDDLPKVpfUejwr3iWI5fa9FFayhgkl0BEjBakcEQgVuhAlDdqXJsRuMCjtnr2Vhkqt3+C/hfx6f/Uoi4KIS3MzVUOhmbFsBIbCPVzKp1emBOE3NE= paluh@nixos"
]
name = "Tomasz Rybarczyk"


[waalge]
admin = true
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH8M0WwpkjFbabVYEnrZp2Z1bThwiInd7xB3tfWZAHfv"
]
name = "Dominic"
